### ISSUE TITLE
會當匯入的資料

### ISSUE THREAD

**Issue by sih4sing5hong5** [Taiwanese-Corpus/hue7jip8#23]
- [x] 2005.txt.gz #43
- [x] 2009.分詞.gz #44
- [x] icorpus.txt.gz
- [x] moedict_su.分詞.gz #39
- [x] napheng.分詞.gz https://github.com/twgo/twisas/blob/master/twisas/management/commands/匯入台文語料庫2版文本.py
- [x] su-lui.分詞.gz #30 
- [x] twisas.分詞.gz
- [x] 例句.分詞.gz
- [x] 數位典藏.分詞.gz #41
- [ ] 陳先生60句.分詞.gz
- [ ] 陳先生提供的語句.分詞.gz
